// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartRunTracker.Infrastructure.Persistence;

#nullable disable

namespace SmartRunTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531102844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.PlannedSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("TargetDistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetPaceSecondsPerKm")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingWeekId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledFor");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("planned_sessions", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunnerAvailableDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("RunnerProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunnerProfileId", "Day")
                        .IsUnique();

                    b.ToTable("runner_available_days", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunnerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreferredWorkoutsPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("TrainingDayPreferenceMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("runner_profiles", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunningGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("GoalDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TargetDistanceKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("TargetPaceSecondsPerKm")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("running_goals", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.TrainingWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RunningGoalId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TargetWeekDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TargetWorkoutCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("RunningGoalId");

                    b.HasIndex("UserId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("training_weeks", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("PlannedSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Rpe")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlannedSessionId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("workouts", (string)null);
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.PlannedSession", b =>
                {
                    b.HasOne("SmartRunTracker.Domain.Entities.TrainingWeek", "TrainingWeek")
                        .WithMany("PlannedSessions")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunnerAvailableDay", b =>
                {
                    b.HasOne("SmartRunTracker.Domain.Entities.RunnerProfile", "RunnerProfile")
                        .WithMany("AvailableDays")
                        .HasForeignKey("RunnerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunnerProfile");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunnerProfile", b =>
                {
                    b.HasOne("SmartRunTracker.Domain.Entities.User", "User")
                        .WithOne("RunnerProfile")
                        .HasForeignKey("SmartRunTracker.Domain.Entities.RunnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunningGoal", b =>
                {
                    b.HasOne("SmartRunTracker.Domain.Entities.User", "User")
                        .WithMany("RunningGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.TrainingWeek", b =>
                {
                    b.HasOne("SmartRunTracker.Domain.Entities.RunningGoal", "RunningGoal")
                        .WithMany("TrainingWeeks")
                        .HasForeignKey("RunningGoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRunTracker.Domain.Entities.User", "User")
                        .WithMany("TrainingWeeks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunningGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.Workout", b =>
                {
                    b.HasOne("SmartRunTracker.Domain.Entities.PlannedSession", "PlannedSession")
                        .WithOne("CompletedWorkout")
                        .HasForeignKey("SmartRunTracker.Domain.Entities.Workout", "PlannedSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartRunTracker.Domain.Entities.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.PlannedSession", b =>
                {
                    b.Navigation("CompletedWorkout");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunnerProfile", b =>
                {
                    b.Navigation("AvailableDays");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.RunningGoal", b =>
                {
                    b.Navigation("TrainingWeeks");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.TrainingWeek", b =>
                {
                    b.Navigation("PlannedSessions");
                });

            modelBuilder.Entity("SmartRunTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("RunnerProfile");

                    b.Navigation("RunningGoals");

                    b.Navigation("TrainingWeeks");

                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
